# Generated by Django 3.2.25 on 2025-03-18 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_ID', models.IntegerField(unique=True)),
                ('Photo', models.ImageField(upload_to='Employee_profile')),
                ('Name', models.CharField(max_length=50)),
                ('Phone_Number', models.BigIntegerField(unique=True)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=10)),
                ('Location', models.CharField(max_length=50)),
                ('merge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Emp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
