# Generated by Django 3.2.25 on 2025-03-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_details',
            name='Role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
