# Generated by Django 3.2.25 on 2025-03-20 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_employee_details_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=50)),
                ('StartTime', models.DateTimeField(auto_now_add=True)),
                ('EndTime', models.DateTimeField(null=True)),
                ('merge1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Task', to='App1.employee_details')),
            ],
        ),
    ]
