# Generated by Django 3.2.25 on 2025-03-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_employee_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_tasks',
            old_name='merge1',
            new_name='Employees',
        ),
    ]
